## tags to ask about:
## farm


def make_ind_dict():

    return {
        "Human Resources": [
            "Call Center",
            "Employee Benefits",
            "Human Resources",
            "Staffing Agency",
            "communications",
            "headhunter",
            "headhunters",
            "talent",
            "hr",
            "recruiting",
        ],
        "Delivery Services": [
            "Courier Service",
            "Packaging Services",
            "Office Administration",
            "Delivery",
        ],
        "Marketing": [
            "Ad Exchange",
            "Ad Network",
            "Ad Retargeting",
            "Ad Server",
            "Ad Targeting",
            "Advertising",
            "Advertising Platforms",
            "Affiliate Marketing",
            "Local Advertising",
            "Mobile Advertising",
            "Outdoor Advertising",
            "SEM",
            "Video Advertising",
            "marketing",
            "digital marketing",
            "seo",
            "advertising and marketing",
            "content distribution",
        ],
        "Agriculture and Farming": [
            "Agriculture",
            "Animal Feed",
            "Aquaculture",
            "Equestrian",
            "Farming",
            "Forestry",
            "Horticulture",
            "Livestock",
            "garden",
        ],
        "AgTech": [
            "AgTech",
            "Hydroponics",
            "Precision Farming",
            "Livestock Monitoring",
            "Precision Aquaculture",
            "Precision Forestry",
            "Smart Greenhouse",
            "agritech",
        ],
        "Apps": [
            "App Discovery",
            "Apps",
            "Consumer Applications",
            "Enterprise Applications",
            "Mobile Apps",
            "Reading Apps",
            "Web Apps",
        ],
        "Biotechnology": [
            "Bioinformatics",
            "Biometrics",
            "Biotechnology",
            "Genetics",
            "Neuroscience",
            "Quantified Self",
            "biopharma",
            "biotech",
        ],
        "Life Sciences": [
            "life science",
            "life sciences",
        ],
        "Clothing and Apparel": [
            "Laundry",
            "Dry-cleaning",
            "Shoes",
            "Clothing",
            "jewelry and watch retail",
        ],
        "Commerce": [
            "Auctions",
            "Classifieds",
            "Collectibles",
            "Consumer Reviews",
            "Coupons",
            "Flash Sale",
            "Gift",
            "Gift Card",
            "Gift Exchange",
            "Gift Registry",
            "Group Buying",
            "Local Shopping",
            "Made to Order",
            "Personalization",
            "Point of Sale",
            "Price Comparison",
            "Rental",
            "Retail",
            "Shopping",
            "Shopping Mall",
            "Sporting Goods",
            "Vending",
            "Concessions",
            "Wholesale",
            "commerce",
            "auction",
        ],
        "E-Commerce": [
            "E-Commerce",
            "E-Commerce Platforms",
            "Virtual Goods",
            "Social Shopping",
            "Online Auctions",
            "Retail Technology",
            "online marketplace",
            "marketplaces",
            "mobile commerce",
            "marketplace",
            "ecommerce",
            "platforms and marketplaces",
            "d2c",
        ],
        "Family Products": ["Baby", "Children", "Family", "Parenting"],
        "Social Networks": [
            "dating app",
            "social media",
            "social network",
            "creator economy",
            "Social Media Advertising",
            "sales and marketing",
        ],
        "Consumer Electronics": [
            "Consumer Electronics",
            "Electronics",
            "Mobile Devices",
        ],
        "IoT": ["Internet of Things", "IoT", "Smart Home", "Wearables"],
        "Consumer Goods": [
            "Comics",
            "Consumer Goods",
            "Cosmetics",
            "DIY",
            "Eyewear",
            "Fast-Moving Consumer Goods",
            "Flowers",
            "Furniture",
            "Green Consumer Goods",
            "Handmade",
            "Shoes",
            "Tobacco",
            "Toys",
            "consumer durables",
            "other consumer products and services",
            "consumer non-durables",
            "Consumer Non-Durables",
        ],
        "Consumer Services": [
            "consumer services general",
            "retail general",
            "consumer services",
        ],
        "Supply Chain": [
            "supply chain",
            "trucking",
            "railroad",
            "freight delivery",
            "supply chain Logistics",
            "supply chain management",
            "Logistics",
            "supply chain and logistics",
        ],
        "Restaurants": [
            "restaurants and leisure",
            "Catering",
            "Distillery",
            "Food Trucks",
            "Restaurants",
            "wineries and breweries",
            "Winery",
            "Wineries",
            "restaurant",
        ],
        "Travel and Tourism": [
            "Adventure Travel",
            "Business Travel",
            "Museums and Historical Sites",
            "Travel",
            "Travel Accommodations",
            "Travel Agency",
            "Vacation Rental",
            "airline",
            "Parks",
            "Resorts",
            "Timeshare",
            "Tour Operator",
            "Tourism",
            "travel and tourism",
        ],
        "Manufacturing": ["Manufacturing", "building materials"],
        "Raw Materials": [
            "minerals",
            "metals",
            "mining",
            "metals and minerals",
            "materials",
        ],
        "Women's Products": ["women's health", "femtech"],
        "Data and Analytics": [
            "Analytics",
            "Application Performance Management",
            "Big Data",
            "Bioinformatics",
            "Business Intelligence",
            "Consumer Research",
            "Data Integration",
            "Data Mining",
            "Data Visualization",
            "Database",
            "Geospatial",
            "Location Based Services",
            "Market Research",
            "Predictive Analytics",
            "Product Research",
            "Test and Measurement",
            "Text Analytics",
            "Usability Testing",
            "Data",
        ],
        "Design": [
            "CAD",
            "Fashion",
            "Graphic Design",
            "Human Computer Interaction",
            "Industrial Design",
            "Interior Design",
            "Mechanical Design",
            "Product Design",
            "Usability Testing",
            "UX Design",
            "Web Design",
            "Design",
        ],
        "Education": [
            "Alumni",
            "College Recruiting",
            "Continuing Education",
            "Corporate Training",
            "Education",
            "Edutainment",
            "Language Learning",
            "Music Education",
            "Personal Development",
            "Primary Education",
            "Secondary Education",
            "Skill Assessment",
            "STEM Education",
            "Textbook",
            "Training",
            "Tutoring",
            "Vocational Education",
            "universities",
            "education services",
        ],
        "EdTech": ["EdTech", "E-Learning", "MOOC"],
        "Energy": [
            "Battery",
            "Biofuel",
            "Biomass Energy",
            "Clean Energy",
            "Electrical Distribution",
            "Energy",
            "Energy Efficiency",
            "Energy Management",
            "Energy Storage",
            "Fossil Fuels",
            "Fuel",
            "Fuel Cell",
            "Oil and Gas",
            "Power Grid",
            "Renewable Energy",
            "Solar",
            "Wind Energy",
            "oil",
        ],
        "Events": [
            "Concerts",
            "Event Management",
            "Event Promotion",
            "Events",
            "Nightclubs",
            "Nightlife",
            "Reservations",
            "Ticketing",
            "Wedding",
        ],
        "Cybersecurity": ["cybersecurity", "privacy and security"],
        "Food and Beverage": [
            "Bakery",
            "Coffee",
            "Confectionery",
            "Cooking",
            "Food and Beverage",
            "Food Delivery",
            "Food Processing",
            "Fruit",
            "Grocery",
            "Nutrition",
            "Recipes",
            "Seafood",
            "Snack Food",
            "Tea",
            "food, beverages and tobacco",
            "food products",
        ],
        "Alcohol": ["Craft Beer", "Wine And Spirits", "Spirits", "Brewing"],
        "FoodTech": ["foodtech"],
        "Transportation": [
            "micro-mobility",
            "car",
            "electric vehicle",
            "vehicles",
            "mobility",
            "transportation",
        ],
        "Sustainable Products": [
            "Farmers Market",
            "Organic Food",
            "Farm-to-table",
            "Locally grown",
            "local farm",
            "sustainability",
        ],
        "Gaming": [
            "Casual Games",
            "Console Games",
            "Contests",
            "Fantasy Sports",
            "Gambling",
            "Gamification",
            "Gaming",
            "MMO Games",
            "Online Games",
            "PC Games",
            "Serious Games",
            "Video Games",
            "casinos and gaming",
            "mobile gaming",
        ],
        "Residential Real Estate": ["residential real estate"],
        "Commercial Real Estate": ["commercial real estate"],
        "Real Estate": [
            "property management",
            "property",
            "real estate",
            "estate",
            "real estate investment",
        ],
        "PropTech": ["proptech", "prop tech"],
        "Construction": [
            "construction and industrial equipment)",
            "construction",
            "construction and engineering",
        ],
        "Government and Military": [
            "CivicTech",
            "Government",
            "GovTech",
            "Law Enforcement",
            "Military",
            "National Security",
            "Politics",
            "Public Safety",
            "Social Assistance",
        ],
        "Health": [
            "Alternative Medicine",
            "Assisted Living",
            "Assistive Technology",
            "Cannabis",
            "Child Care",
            "Clinical Trials",
            "Cosmetic Surgery",
            "Dental",
            "Diabetes",
            "Elder Care",
            "Emergency Medicine",
            "Employee Benefits",
            "Fertility",
            "First Aid",
            "Genetics",
            "Health Care",
            "Health Diagnostics",
            "Home Health Care",
            "Hospital",
            "Medical",
            "Medical Device",
            "mHealth",
            "Nursing and Residential Care",
            "Nutraceutical",
            "Nutrition",
            "Outpatient Care",
            "Personal Health",
            "Rehabilitation",
            "Therapeutics",
            "Wellness",
            "health",
            "healthcare general",
            "medicine",
            "fitness",
            "other healthcare",
            "lifestyle and wellness",
            "consumer health",
            "senior care",
        ],
        "HealthTech": [
            "caretech",
            "healthtech",
            "Electronic Health Record",
            "EHR",
            "healthcare technology systems",
            "medical devices and equipment",
            "digital health",
            "digital healthcare",
            "medical devices",
        ],
        "InsurTech": ["InsurTech"],
        "Telecommunications": [
            "wireless communications equipment",
            "communications infrastructure",
            "Telecommunications",
            "messaging and telecommunications",
        ],
        "Pet Care": ["Veterinary", "Pet Care", "Pet Grooming", "PetTech", "Pet"],
        "Information Technology": ["Information Technology", "IT", "it infrastructure"],
        "eSports": ["eSports", "Fantasy Sports"],
        "Journalism": ["newspapers and news services", "news", "newspaper"],
        "Green Energy": [
            "Biofuel",
            "Biomass Energy",
            "Clean Energy",
            "CleanTech",
            "Energy Efficiency",
            "Green Building",
            "GreenTech",
            "Recycling",
            "Renewable Energy",
            "Solar",
            "Wind Energy",
            "clean technology",
            "electric vehicle",
            "climate tech",
            "climate",
        ],
        "Pharmaceuticals": [
            "pharmaceuticals and biotechnology",
            "pharmaceuticals",
            "Biopharma",
            "Pharmaceutical",
            "Biopharma",
        ],
        "Media and Entertainment": [
            "Animation",
            "Broadcasting",
            "Film",
            "Film Distribution",
            "Film Production",
            "Motion Capture",
            "TV",
            "TV Production",
            "Video",
            "Video Editing",
            "Video on Demand",
            "Video Streaming",
            "media and internet",
            "Media",
            "Media and Entertainment",
            "sports",
        ],
        "Multimedia, Games & Graphics Software": [
            "multimedia, games and graphics software",
            "Multimedia",
            "LED",
            "digital media",
        ],
        "Neural Networks": ["Neural Network"],
        "Web3": ["web3", "defi"],
        "Crypto": ["crypto"],
        "Blockchain": ["Blockchain"],
        "Cloud Services": [
            "cloud infrastructure",
            "web services and apps",
            "cloud computing",
        ],
        "DeFi": ["defi", "decentralized finance"],
        "Extended Reality": [
            "Augmented Reality",
            "AR",
            "Mixed Reality",
            "Virtual Reality",
            "MR",
            "VR",
            "simulation",
            "Virtual World",
        ],
        "Software": [
            "software",
            "saas",
            "retail software",
            "internet software and services",
            "dev tools",
            "applications",
            "developer tools",
        ],
        "SaaS": ["SaaS", "saas enterprise"],
        "IaaS": ["iaas"],
        "B2B Software": ["b2b software"],
        "Legal": ["law", "legal", "law firms", "law firms and legal services"],
        "LegalTech": ["legaltech", "legal tech"],
        "Aerospace": ["aerospace"],
        "Technology Hardware": [
            "technology hardware",
            "peripheral devices",
            "semiconductors",
            "technology infrastructure",
            "electronic components",
            "storage and peripherals",
            "other hardware",
            "hardware",
            "drones",
        ],
        "DeepTech": [
            "deeptech",
            "quantum computing",
            "artificial intelligence and machine learning",
            "deep tech",
            "computer vision",
            "AI",
            "Artificial Intelligence",
            "Speech Recognition",
            "Intelligent Systems",
            "Facial Recognition",
            "Image Recognition",
            "Machine Learning",
            "ML",
            "NLP",
            "Natural Language Processing",
        ],
        "FinTech": ["fintech", "transaction processing", "fintech [august 2020]"],
        "Insurance": ["insurance"],
        "Mobile": ["mobile"],
        "Robotics": ["robotics"],
        "Mobile": ["mobile"],
        "Childcare": ["childcare"],
    }


def make_tool_dict():

    return {
        "AI": [
            "AI",
            "Artificial Intelligence",
            "Speech Recognition",
            "Intelligent Systems",
        ],
        "Computer Vision": [
            "Facial Recognition",
            "Image Recognition",
            "computer vision",
        ],
        "ML": ["Machine Learning", "ML", "NLP", "Natural Language Processing"],
        "P2P": ["peer to peer"],
        "ESG": ["esg", "underrepresented", "poc", "social responsibility", "dei"],
        "Agnostic": ["agnostic"],
        "SME": ["sme tech", "sme"],
        "Agnostic": ["agnostic"],
        "SMB": ["smb"],
        "B2B": [
            "B2B",
            "Business Products And Services",
            "commercial services",
            "business products and services (b2b)",
        ],
        "B2C": ["B2C", "Consumer Products And Services", "Consumer", "consumer tech"],
    }
