## to-do
# Need to differentiate between traditional schools and platforms, e-learning and such

### CHANGE LOG ###
## 9/26/22 
    # 12:59 pm
    # 1:08 pm
    # 1:26 pm
    # 1:32 pm


def make_ind_dict():

    return {
        "Public Relations": [
            "public relations",
            "personal branding",
        ],
        "Accounting": ["accounting"],
        "3D Printing": [
            "3d printing",
            "3d technology",
        ],
        "Business Development": ["business development"],
        "Human Resources": [
            "Employee Benefits",
            "Human Resources",
            "Staffing Agency",
            "headhunter",
            "headhunters",
            "talent",
            "hr",
            "recruiting",
        ],
        "Delivery Services": [
            "Courier Service",
            "Packaging Services",
            "Office Administration",
            "Delivery",
            "delivery service",
            "Food Delivery",
            "shipping",
            "shipping broker",
            "same day delivery",
        ],
        "Marketing": [
            "Ad Exchange",
            "Ad Network",
            "Ad Retargeting",
            "Ad Server",
            "Ad Targeting",
            "Advertising",
            "Advertising Platforms",
            "Affiliate Marketing",
            "Local Advertising",
            "Mobile Advertising",
            "Outdoor Advertising",
            "SEM",
            "Video Advertising",
            "marketing",
            "digital marketing",
            "seo",
            "advertising and marketing",
            "content distribution",
            "app marketing",
            "brand marketing",
            "cause marketing",
            "content marketing",
            "content syndication",
            "marketing automation",
            "digital signage",
            "direct marketing",
            "email marketing",
            "content discovery",
            "sponsorship",
            "social media marketing",
            "sales and marketing",
        ],
        "Sales": [
            "lead management",
            "lead generation",
            "procurement",
            "sales automation",
            "direct sales",
            "sales",
        ],
        "Agriculture and Farming": [
            "Agriculture",
            "Animal Feed",
            "Aquaculture",
            "Equestrian",
            "Farming",
            "Forestry",
            "Horticulture",
            "Livestock",
            "garden",
        ],
        "AgTech": [
            "AgTech",
            "Hydroponics",
            "Precision Farming",
            "Livestock Monitoring",
            "Precision Aquaculture",
            "Precision Forestry",
            "Smart Greenhouse",
            "agritech",
        ],
        "Software Development": [
            "web development",
            "software engineering",
        ],
        "Biotechnology": [
            "Bioinformatics",
            "Biometrics",
            "Biotechnology",
            "Genetics",
            "Neuroscience",
            "Quantified Self",
            "biopharma",
            "biotech",
        ],
        "Life Sciences": [
            "life science",
            "life sciences",
        ],
        "Clothing and Apparel": [
            "Shoes",
            "Clothing",
            "jewelry and watch retail",
            "fashion",
            "jewelry",
            "lingerie",
            "Eyewear",
        ],
        "Commerce": [
            "Auctions",
            "Classifieds",
            "Collectibles",
            "Consumer Reviews",
            "Coupons",
            "Flash Sale",
            "Gift",
            "Gift Card",
            "Gift Exchange",
            "Gift Registry",
            "Group Buying",
            "Local Shopping",
            "Made to Order",
            "Personalization",
            "Point of Sale",
            "Price Comparison",
            "Rental",
            "Retail",
            "Shopping",
            "Shopping Mall",
            "Sporting Goods",
            "Vending",
            "Concessions",
            "Wholesale",
            "commerce",
            "auction",
        ],
        "Consulting": [
            "advice",
            "consulting",
            "management consulting",
            "environmental consulting",
            "career planning",
        ],
        "E-Commerce": [
            "E-Commerce",
            "E-Commerce Platforms",
            "Virtual Goods",
            "Social Shopping",
            "Online Auctions",
            "Retail Technology",
            "mobile commerce",
            "ecommerce",
            "d2c",
        ],
        "Retail Investing Products": ["trading platform"],
        "Family": [
            "Baby",
            "Children",
            "Family",
            "Parenting",
            "childcare",
            "elderly",
            "funerals",
        ],
        "Social Media": [
            "dating app",
            "social media",
            "social network",
            "creator economy",
            "Social Media Advertising",
            "blogging platforms",
            "online forums",
            "photo sharing",
            "dating",
            "private social networking",
            "professional networking",
            "social media management",
            "content",
            "content creators",
            "q&a",
        ],
        "IoT": [
            "Internet of Things",
            "IoT",
            "Smart Home",
            "Wearables",
            "smart building",
            "smart cities",
            "virtual assistant",
            "indoor positioning",
        ],
        "Consumer Durables":[
            "Comics",
            "consumer durables",
        ],
        "Consumer Services": [
            "consumer services general",
            "retail general",
            "consumer services",
        ],
        "Service Industry": ["service industry"],
        "Laundry and Dry-Cleaning": [
            "laundry and dry-cleaning",
            "Laundry",
            "Dry-cleaning",
        ],
        "User Support": [
            "customer service",
            "technical support",
            "field support",
            "guides",
            "call center",
        ],
        "Supply Chain": [
            "supply chain",
            "trucking",
            "railroad",
            "freight delivery",
            "supply chain Logistics",
            "supply chain management",
            "Logistics",
            "supply chain and logistics",
            "fleet management",
            "freight service",
            "water transportation",
        ],
        "Restaurants": [
            "restaurants and leisure",
            "Catering",
            "Distillery",
            "Food Trucks",
            "Restaurants",
            "wineries and breweries",
            "Winery",
            "Wineries",
            "restaurant",
        ],
        "Travel and Tourism": [
            "Adventure Travel",
            "Business Travel",
            "Museums and Historical Sites",
            "Travel",
            "Travel Accommodations",
            "Travel Agency",
            "Vacation Rental",
            "airline",
            "Parks",
            "Resorts",
            "Tour Operator",
            "Tourism",
            "travel and tourism",
            "hospitality",
            "hotel",
            "timeshare",
        ],
        "Manufacturing": [
            "Manufacturing",
            "building materials",
            "building material",
            "plastics and rubber manufacturing",
            "electronic design automation (eda)",
            "laser",
            "textiles",
            "machinery manufacturing",
            "semiconductor",
            "industrial manufacturing",
            "chemical",
        ],
        "Fraud Detection": [
            "fraud detection",
        ],
        "Franchise": [
            "franchise",
        ],
        "Industrial Engineering and Automation": [
            "industrial automation",
            "industrial engineering",
            "robotics",
        ],
        "Product Management": [
            "product management",
        ],
        "Innovation Management": [
            "intellectual property",
            "innovation management",
        ],
        "Raw Materials": [
            "minerals",
            "metals",
            "mining",
            "metals and minerals",
            "materials",
            "mineral",
            "mining technology",
            "natural resources",
            "water",
            "precious metals",
            "water purification",
        ],
        "Women's Products": [
            "women's health", 
            "femtech", 
            "women's", 
            'beauty', 
            "Cosmetics",
        ],
        "Design": [
            "CAD",
            "Human Computer Interaction",
            "Industrial Design",
            "Mechanical Design",
            "Product Design",
            "Usability Testing",
            "UX Design",
            "Web Design",
            "Design",
            "Graphic Design",
        ],
        "Education": [
            "Alumni",
            "College Recruiting",
            "Continuing Education",
            "Corporate Training",
            "Education",
            "Edutainment",
            "Language Learning",
            "Music Education",
            "Personal Development",
            "Primary Education",
            "Secondary Education",
            "Skill Assessment",
            "STEM Education",
            "Textbook",
            "Training",
            "Tutoring",
            "Vocational Education",
            "universities",
            "education services",
            "charter schools",
            "audiobooks",
            "ebooks",
            "higher education",
            "EdTech",
            "E-Learning",
            "MOOC",
            "reading apps",
        ],
        "Physical Storage": ["warehousing", "self-storage"],
        "Energy": [
            "Battery",
            "Biofuel",
            "Biomass Energy",
            "Electrical Distribution",
            "Energy",
            "Energy Efficiency",
            "Energy Management",
            "Energy Storage",
            "Fossil Fuels",
            "Fuel",
            "Fuel Cell",
            "Oil and Gas",
            "Power Grid",
            "oil",
            "nuclear",
            "climate",
        ],
        "Events": [
            "Concerts",
            "Event Management",
            "Event Promotion",
            "Events",
            "Nightclubs",
            "Nightlife",
            "Reservations",
            "Ticketing",
            "Wedding",
            "music venues",
        ],
        "Cybersecurity": [
            "cybersecurity",
            "privacy and security",
            "cyber security",
            "network security",
            "penetration testing",
            "privacy",
        ],
        "Consumer Durables": [
            "Bakery",
            "Coffee",
            "Confectionery",
            "Cooking",
            "Food and Beverage",
            "Food Processing",
            "Fruit",
            "Grocery",
            "Nutrition",
            "Recipes",
            "Seafood",
            "Snack Food",
            "Tea",
            "food, beverages and tobacco",
            "food products",
            "vending and concessions",
            "DIY",
            "Tobacco",
            "other consumer products and services",
            "consumer non-durables",
            "Consumer Non-Durables",
        ],
        "Alcohol": ["Craft Beer", "Wine And Spirits", "Spirits", "Brewing"],
        "FoodTech": ["foodtech"],
        "Transportation": [
            "micro-mobility",
            "mobility",
            "transportation",
            "taxi service",
            "air transportation",
            "last mile transportation",
            "public transportation",
            "ride sharing",
            "parking",
        ],
        "Sustainablility": [
            "Organic Food",
            "Farm-to-table",
            "sustainability",
            "organic",
            "pollution control",
            "CleanTech",
            "Clean Energy",
            "environmental engineering",
            "GreenTech",
            "Renewable Energy",
            "Solar",
            "Wind Energy",
            "green energy",
            "clean technology",
            "climate tech",
            "Green Building",
        ],
        "Real Estate": [
            "property",
            "real estate",
            "estate",
            "real estate investment",
            "leasing",
            "rental property",
            "commercial real estate",
            "residential real estate",
            "residential",
            "property management",
            "facility management",
            "facilities support services",
            "building maintenance",
            "home services",
            "proptech",
            "prop tech",
            "coworking",
        ],
        "Construction": [
            "construction and industrial equipment)",
            "construction",
            "construction and engineering",
            "property development",
        ],
        "Home and Garden": [
            "home and garden",
            "home decor",
            "home improvement",
            "home renovation",
            "Landscaping",
            "Architecture",
            "Interior Design",
            "Lighting",
            "Furniture",
            "Flowers",
            "housekeeping service",
        ],
        "Government and Military": [
            "CivicTech",
            "Government",
            "GovTech",
            "Law Enforcement",
            "Military",
            "National Security",
            "Politics",
            "Public Safety",
            "Social Assistance",
            "Government and Military",
            "homeland security",
        ],
        "Engineering": [
            "chemical engineering", 
            "civil engineering", 
            "mechanical engineering"
        ],
        "Health": [
            "Alternative Medicine",
            "Assisted Living",
            "Assistive Technology",
            "Cannabis",
            "Child Care",
            "Clinical Trials",
            "Cosmetic Surgery",
            "Dental",
            "Diabetes",
            "Elder Care",
            "Emergency Medicine",
            "Employee Benefits",
            "Fertility",
            "First Aid",
            "Genetics",
            "Health Care",
            "Health Diagnostics",
            "Home Health Care",
            "Hospital",
            "Medical",
            "Medical Device",
            "Nursing and Residential Care",
            "Nutraceutical",
            "Nutrition",
            "Outpatient Care",
            "Personal Health",
            "Rehabilitation",
            "Therapeutics",
            "Wellness",
            "health",
            "healthcare general",
            "medicine",
            "fitness",
            "other healthcare",
            "lifestyle and wellness",
            "consumer health",
            "senior care",
            "dietary supplements",
            "medical devices",
        ],
        "HealthTech": [
            "caretech",
            "healthtech",
            "Electronic Health Record",
            "EHR",
            "healthcare technology systems",
            "medical devices and equipment",
            "digital health",
            "digital healthcare",
            "electronic health record (ehr)",
            "mHealth",
        ],
        "InsurTech": ["InsurTech"],
        "Telecommunications": [
            "wireless communications equipment",
            "communications infrastructure",
            "Telecommunications",
            "messaging and telecommunications",
            "communications",
            "voip",
            "FoIP",
            "messaging",
            "email",
            "sms",
            "video chat",
            "satellite communication",
            "optical communication",
        ],
        "Pet Care": ["Veterinary", "Pet Care", "Pet Grooming", "PetTech", "Pet"],
        "Information Technology": [
            "Information Technology",
            "IT",
            "it infrastructure",
            "business information systems",
            "it management",
            "information and communications technology (ict)",
            "reputation",
            "identity management",
        ],
        "Pharmaceuticals": [
            "pharmaceuticals and biotechnology",
            "pharmaceuticals",
            "Biopharma",
            "Pharmaceutical",
            "Biopharma",
            "biotechnology",
        ],
        "Arts and Entertainment": [
            "celebrity",
            "Animation",
            "Broadcasting",
            "Film",
            "Film Distribution",
            "Film Production",
            "Motion Capture",
            "TV",
            "TV Production",
            "Video",
            "Video Editing",
            "media and internet",
            "Media",
            "Media and Entertainment",
            "sports",
            "Art",
            "audio",
            "baseball",
            "basketball",
            "music",
            "digital entertainment",
            "golf",
            "hockey",
            "cricket",
            "independent music",
            "soccer",
            "performing arts",
            "podcast",
            "photography",
            "musical instruments",
            "internet radio",
            "Publishing",
            "Casual Games",
            "Console Games",
            "Contests",
            "Fantasy Sports",
            "Gambling",
            "Gamification",
            "Gaming",
            "MMO Games",
            "Online Games",
            "PC Games",
            "Serious Games",
            "Video Games",
            "casinos and gaming",
            "mobile gaming",
            "Casino",
            "eSports",
            "Fantasy Sports",
        ],
        "Productivity Tools": [
            "productivity tools",
            "project management",
            "quality assurance",
            "task management",
        ],
        "Translation Service": ["translation service"],
        "News": [
            "social news",
            "journalism",
            "newspapers and news services",
            "news",
            "newspaper",
        ],
        "Streaming Platforms": [
            "music streaming",
            "Video Streaming",
            "Video on Demand",
            "podcast streaming",
        ],
        "Search Software": [
            "search engine",
            "semantic search",
            "vertical search",
            "visual search",
        ],
        "Multimedia and Graphics Software": [
            "multimedia, games and graphics software",
            "Multimedia",
            "LED",
            "photo editing",
            "digital media",
            "presentation software",
            "printing",
            "presentations",
            "Data Visualization",
        ],
        "Crypto": [
            "crypto",
            "bitcoin",
            "cryptocurrency",
            "ethereum",
            "virtual currency",
        ],
        "Web Services": [
            "cloud infrastructure",
            "data center",
            "cloud computing",
            "cloud data services",
            "cloud management",
            "cloud security",
            "cloud storage",
            "data storage",
            "private cloud",
            "web hosting",
            "content delivery network",
            "isp",
        ],
        "Outdoor Activities": ["cycling", "swimming", "outdoors"],
        "DeFi": ["defi", "decentralized finance"],
        "Extended Reality": [
            "Augmented Reality",
            "AR",
            "Mixed Reality",
            "Virtual Reality",
            "MR",
            "VR",
            "simulation",
            "Virtual World",
        ],
        "Software": [
            "software",
            "retail software",
            "internet software and services",
            "dev tools",
            "developer tools",
            "open source",
            "operating systems",
            "developer apis",
            "developer platform",
            "embedded software",
            "ios",
            "android",
            "online portals",
            "Enterprise Software",
            "desktop apps",
            "Consumer Applications", 
            "browser extensions",
            "web browsers",
            "web apps",
            "mobile apps",
            "apps",
        ],
        "Men's Products": ["men's"],
        "Legal": [
            "law",
            "legal",
            "law firms",
            "law firms and legal services",
            "ediscovery",
        ],
        "Outsourcing": ["outsourcing", "freelance", "creative agency"],
        "LegalTech": ["legaltech", "legal tech"],
        "Aerospace": ["aerospace", "space travel"],
        "Hardware": [
            "technology hardware",
            "peripheral devices",
            "semiconductors",
            "technology infrastructure",
            "electronic components",
            "storage and peripherals",
            "other hardware",
            "hardware",
            "drones",
            "application specific integrated circuit (asic)",
            "communication hardware",
            "gpu",
            "Consumer Electronics",
            "Electronics",
            "Mobile Devices",
            "drone management",
            "network hardware",
            "Sensor",
            "field-programmable gate array (fpga)",
            "embedded systems",
            "qr codes",
        ],
        "DeepTech": [
            "deeptech",
            "quantum computing",
            "artificial intelligence and machine learning",
            "deep tech",
            "computer vision",
            "AI",
            "Artificial Intelligence",
            "Speech Recognition",
            "Intelligent Systems",
            "Facial Recognition",
            "Image Recognition",
            "Machine Learning",
            "ML",
            "NLP",
            "Natural Language Processing",
        ],
        "FinTech": [
            "fintech",
            "transaction processing",
            "fintech [august 2020]",
            "billing",
            "payments",
            "mobile payments",
            "personal finance",
            "debt collections",
        ],
        "Insurance": [
            "insurance",
            "auto insurance",
            "commercial insurance",
            "life insurance",
            "health insurance",
            "property insurance",
        ],
        "Security": ["physical security", "intrusion detection"],
        "Automotive": [
            "automotive",
            "autonomous vehicles",
            "recreational vehicles",
            "electric vehicles",
            "car",
            "electric vehicle",
            "vehicles",
        ],
        "Boating and Marine": [
            "boating",
            "marine technology",
            "marine transportation",
            "ports and harbors",
        ],
        "Philanthropy": ["charity", "underserved children"],
        "Database Management": [
            "cms",
            "contact management",
            "crm",
            "drm",
            "file sharing",
            "data center automation",
            "knowledge management",
            "Database",
            "social crm",
        ],
        "Crowdfunding": ["crowdfunding", "funding platform"],
        "Crowdsourcing": ["crowdsourcing"],
        "Multi-Level Marketing": ["multi-level marketing"],
        "Employment": ["employment", "virtual workforce"],
        "Enterprise Software": [
            "enterprise resource planning (erp)",
            "enterprise software",
            "document management",
            "document preparation",
            "e-signature",
            "management information systems",
            "meeting software",
            "Enterprise Applications",
            "video conferencing",
            "unified communications",
        ],
        "Location Based Services": [
            "Location Based Services",
            "navigation",
            "gps",
            "Mapping Services",
        ],
        "Waste Management": ["waste management"],
        "Sex Industry": ["sex industry", "sex tech"],
        "Payment Card Industry (PCI)": [
            "credit cards",
            "credit",
            "debit cards",
        ],
        "Recreation and Leisure": ['social', 'leisure', 'recreation']
    }


def investor_dict():

    return {
        "Angel Investor": ["angel investment"],
        "Private Equity": ["asset management", "hedge funds"],
        "Banking": ["banking", "commercial lending", "consumer lending"],
        "Accelerators and Incubators": [
            "incubators",
            "Accelerators",
        ],
        "Venture Capital": ["venture capital"],
        "Micro Lending": ["micro lending"],
        "Financial Services": ["financial services"],
        "Impact Investing": ["impact investing"],
        "Finance": ["finance"],
        "Financial Exchanges": ['financial exchanges'],
        "Wealth Management": ["wealth management"],
    }


def make_tag_dict():

    return {
        "AI": [
            "AI",
            "Artificial Intelligence",
            "Speech Recognition",
            "Intelligent Systems",
        ],
        "Computer Vision": [
            "Facial Recognition",
            "Image Recognition",
            "computer vision",
        ],
        "ML": ["Machine Learning", "ML", "NLP", "Natural Language Processing"],
        "P2P": ["peer to peer"],
        "ESG": [
            "esg",
            "underrepresented",
            "poc",
            "social responsibility",
            "dei",
            "social impact",
            "lgbt",
            "recycling",
            "Clean Energy",
            "CleanTech",
            "Energy Efficiency",
            "Green Building",
            "GreenTech",
            "Recycling",
            "Renewable Energy",
            "Solar",
            "Wind Energy",
            "clean technology",
            "electric vehicle",
            "climate tech",
            "green consumer goods",
            "climate",
        ],
        "Religious": ['religion'],
        "Agnostic": ["agnostic"],
        "SME": ["sme tech", "sme"],
        "Agnostic": ["agnostic"],
        "SMB": ["smb", "small and medium businesses"],
        "SME": ["sme tech"],
        "Mobile": ["mobile"],
        "A/B Testing": ["a/b testing"],
        "Adult": ["adult"],
        "Advanced Materials": ["advanced materials"],
        "Blockchain": [
            "Blockchain",
        ],
        "Web3": [
            "web3",
            "semantic web",
            "defi",
        ],
        "Open Source": ["open source"],
        "Emerging Markets": ["emerging markets"],
        "Nanotechnology": ["nanotechnology"],
        "Non-Profit": ["non profit"],
        "Virtualization": ["virtualization"],
        "Association": ["association"],
        "Marketplaces": [
            "marketplaces",
            "platforms and marketplaces",
            "marketplace",
            "online marketplace",
            "collaborative consumption",
            "ride sharing",
            "sharing economy",
            "car sharing",
        ],
        "B2B2C": ["b2b2c"],
        "Subscription Services": ["subscription service", "loyalty programs"],
        "SaaS": ["SaaS", "saas enterprise"],
        "IaaS": ["iaas"],
        "PaaS": ["paas"],
        "B2B": [
            "B2B",
            "Business Products And Services",
            "commercial services",
            "business products and services (b2b)",
            "b2b software",
            "b2b saas",
            "commercial",
            "enterprise",
        ],
        "B2C": [
            "B2C",
            "Consumer Products And Services",
            "Consumer",
            "consumer tech",
            "consumer software",
        ],
        "Millennials": ["millennials"],
        "Gen Z": ["generation z"],
        "Youth": ['young adults', 'teenagers',],
        "Neural Networks": ["Neural Network"],
        "Lifestyle": [ "lifestyle"],
        "Local Business": [
            'local business', 
            'local',
            "Farmers Market",
            "Locally grown",
            "local farm",
        ],
        "Data and Analytics": [
            "Analytics",
            "Application Performance Management",
            "Big Data",
            "Bioinformatics",
            "Business Intelligence",
            "Consumer Research",
            "Data Integration",
            "Data Mining",
            "Geospatial",
            "Market Research",
            "Predictive Analytics",
            "Product Research",
            "Test and Measurement",
            "Text Analytics",
            "Usability Testing",
            "Data",
            "information services",
            "prediction markets",
        ],
    }